---
- name: Analyze all VMs in vCenter
  hosts: vcenter_servers
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "vcenterpreprod.basan.mg"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "YOUR_PASSWORD"
    validate_certs: no

  tasks:

    - name: Get all VMs from vCenter
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        folder: "/"   # Query all VMs in root folder
      delegate_to: localhost
      register: all_vms

    - name: Ensure we got some VMs
      ansible.builtin.debug:
        msg: "No VMs found!"
      when: all_vms.virtual_machines | length == 0

    - name: Show all VM names and OS
      ansible.builtin.debug:
        msg: "VM '{{ item.name }}' -> OS: '{{ item.guest_full_name }}', Power State: '{{ item.power_state }}'"
      loop: "{{ all_vms.virtual_machines }}"
      when: all_vms.virtual_machines | length > 0

    - name: Count Linux VMs
      ansible.builtin.set_fact:
        linux_vms: "{{ all_vms.virtual_machines | selectattr('guest_full_name','search','Linux') | list | length }}"

    - name: Count Windows VMs
      ansible.builtin.set_fact:
        windows_vms: "{{ all_vms.virtual_machines | selectattr('guest_full_name','search','Windows') | list | length }}"

    - name: Show summary
      ansible.builtin.debug:
        msg:
          - "Total VMs: {{ all_vms.virtual_machines | length }}"
          - "Linux VMs: {{ linux_vms }}"
          - "Windows VMs: {{ windows_vms }}"
