---
- name: vCenter VM Summary
  hosts: localhost
  gather_facts: no
  vars:
    vcenter_hostname: "vcenterpreprod.basan.mg"
    vcenter_user: "administrator@vsphere.local"
    vcenter_password: "YourPassword"
    validate_certs: no

  tasks:

    - name: Gather all VMs from vCenter
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      register: all_vms
      delegate_to: localhost

    - name: Initialize counters
      set_fact:
        linux_count: 0
        windows_count: 0
        vm_table: []

    - name: Build VM table and count Linux/Windows
      set_fact:
        vm_table: "{{ vm_table + [ {
          'name': (item.guest_name | default('Unknown')),
          'os': (item.guest_fullname | default('Unknown')),
          'power': (item.power_state | default('Unknown'))
        } ] }}"
        linux_count: "{{ (linux_count | int) + 1 if (item.guest_fullname is defined and 'linux' in (item.guest_fullname | lower)) else (linux_count | int) }}"
        windows_count: "{{ (windows_count | int) + 1 if (item.guest_fullname is defined and 'windows' in (item.guest_fullname | lower)) else (windows_count | int) }}"
      loop: "{{ all_vms.virtual_machines | default([]) }}"

    - name: Display VM Table
      debug:
        msg: |
          {% for vm in vm_table %}
          Name: {{ vm.name }} | OS: {{ vm.os }} | Power: {{ vm.power }}
          {% endfor %}

    - name: Display Summary
      debug:
        msg: |
          Total VMs: {{ vm_table | length }}
          Linux VMs: {{ linux_count }}
          Windows VMs: {{ windows_count }}
