---
- name: VMware VM Summary Report
  hosts: vcenter_servers
  connection: local
  gather_facts: false

  vars:
    vcenter_hostname: "YOUR_VCENTER_HOSTNAME"
    vcenter_username: "YOUR_USERNAME"
    vcenter_password: "YOUR_PASSWORD"
    validate_certs: false

  tasks:

    - name: Gather all VMs from vCenter
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
      delegate_to: localhost
      register: all_vms

    - name: Initialize counters
      set_fact:
        linux_count: 0
        windows_count: 0
        vm_report: []

    - name: Build VM report list and count Linux/Windows
      set_fact:
        vm_report: "{{ vm_report + [ {'name': item.guest_name | default('Unknown'),
                                     'os': item.guest_fullname | default('Unknown'),
                                     'power': item.power_state | default('Unknown') } ] }}"
        linux_count: "{{ linux_count + 1 if (item.guest_fullname is defined and 'Linux' in item.guest_fullname) else linux_count }}"
        windows_count: "{{ windows_count + 1 if (item.guest_fullname is defined and 'Windows' in item.guest_fullname) else windows_count }}"
      loop: "{{ all_vms.virtual_machines | default([]) }}"
      loop_control:
        label: "{{ item.guest_name | default('Unknown') }}"

    - name: Display VM Table
      debug:
        msg: |
          {% for vm in vm_report %}
          Name: {{ vm.name }} | OS: {{ vm.os }} | Power: {{ vm.power }}
          {% endfor %}

    - name: Display Summary
      debug:
        msg: |
          Total VMs: {{ vm_report | length }}
          Linux VMs: {{ linux_count }}
          Windows VMs: {{ windows_count }}
