---
- name: Analyse des VMs VMware
  hosts: vcenter_servers
  connection: local
  gather_facts: no

  vars:
    vcenter_hostname: "vcenterpreprod.basan.mg"
    vcenter_username: "your_username"
    vcenter_password: "your_password"

  tasks:
    - name: Récupérer toutes les VMs
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: "/"           # root folder, change if needed
      delegate_to: localhost
      register: all_vms

    - name: Afficher la liste des VMs et leur OS
      ansible.builtin.debug:
        msg: |
          {% for vm in all_vms.virtual_machines %}
          VM: {{ vm.name }}, OS: {{ vm.guest_full_name }}, State: {{ vm.power_state }}
          {% endfor %}

    - name: Compter les VMs Linux
      set_fact:
        linux_vms: "{{ all_vms.virtual_machines | selectattr('guest_id','match','^linux.*') | list }}"

    - name: Compter les VMs Windows
      set_fact:
        windows_vms: "{{ all_vms.virtual_machines | selectattr('guest_id','match','^windows.*') | list }}"

    - name: Afficher le résumé
      ansible.builtin.debug:
        msg: |
          Nombre total de VMs: {{ all_vms.virtual_machines | length }}
          VMs Linux: {{ linux_vms | length }}
          VMs Windows: {{ windows_vms | length }}
