---
- name: Analyse toutes les VMs VMware
  hosts: vcenter_servers
  connection: local
  gather_facts: no

  tasks:
    - name: Récupérer toutes les VMs
      community.vmware.vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        datacenter: "DC - Preprod"   # change to your datacenter
      delegate_to: localhost
      register: vm_facts

    - name: Afficher le nombre total de VMs
      ansible.builtin.debug:
        msg: "Nombre total de VMs : {{ vm_facts.virtual_machines | length }}"

    - name: Séparer Linux et Windows
      ansible.builtin.set_fact:
        linux_vms: "{{ vm_facts.virtual_machines | selectattr('guest_id', 'search', '^linux') | list }}"
        windows_vms: "{{ vm_facts.virtual_machines | selectattr('guest_id', 'search', '^win') | list }}"

    - name: Afficher le nombre de Linux et Windows
      ansible.builtin.debug:
        msg: |
          Linux VMs : {{ linux_vms | length }}
          Windows VMs : {{ windows_vms | length }}

    - name: Afficher les noms des VMs Linux
      ansible.builtin.debug:
        msg: "{{ linux_vms | map(attribute='name') | list }}"

    - name: Afficher les noms des VMs Windows
      ansible.builtin.debug:
        msg: "{{ windows_vms | map(attribute='name') | list }}"
