---
- name: Gérer les VMs VMware
  hosts: vcenter_servers
  connection: local
  gather_facts: no

  tasks:
    - name: Récupérer les informations de la VM
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ vm_name | default(omit) }}"  # Allows querying a single VM or all VMs if name not set
      delegate_to: localhost
      register: vm_info
      failed_when: vm_info.failed is defined and vm_info.failed  # Avoid playbook crash if module fails

    - name: Debug full VM info
      ansible.builtin.debug:
        var: vm_info

    - name: Afficher l'état de toutes les VMs
      ansible.builtin.debug:
        msg: >-
          La VM '{{ item.name }}' est dans l'état de puissance : {{ item.power_state }}
      loop: >-
        {% if vm_info.virtual_machines is defined %}
          {{ vm_info.virtual_machines }}
        {% elif vm_info.vm_info is defined %}
          [ vm_info.vm_info ]
        {% else %}
          []
        {% endif %}
      when: vm_info is defined
