---
- name: Gérer les VMs VMware
  hosts: vcenter_servers
  connection: local

  tasks:
    - name: Récupérer les informations de la VM
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "TNLECSRVDTB55"
      delegate_to: localhost
      register: vm_info

    - name: Afficher l'état de la VM
      ansible.builtin.debug:
        msg: "La VM '{{ vm_info.virtual_machines[0].guest_name }}' est dans l'état de puissance : {{ vm_info.virtual_machines[0].power_state }}"
      when: vm_info.virtual_machines | length > 0
