---
- name: Gérer les VMs VMware
  hosts: vcenter_servers
  connection: local
  gather_facts: no

  vars:
    vm_name: "TNLECSRVDTB55"  # Define your VM name here

  tasks:
    - name: Récupérer les informations de la VM
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: False
        name: "{{ vm_name }}"
      delegate_to: localhost
      register: vm_info
      failed_when: vm_info.failed is defined and vm_info.failed

    - name: Debug full VM info
      ansible.builtin.debug:
        var: vm_info

    - name: Afficher l'état de la VM
      ansible.builtin.debug:
        msg: "La VM '{{ vm_info.virtual_machines[0].name }}' est dans l'état de puissance : {{ vm_info.virtual_machines[0].power_state }}"
      when: vm_info.virtual_machines is defined and vm_info.virtual_machines | length > 0
